---
  - name: Elk playbook
    hosts: elk
    remote_user: azadmin
    become: true
    tasks:
    - name: update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Docker module
      pip:
        name: docker-py
        state: present

    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

    - name: use more memory
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        reload: yes

    - name: download and launch a docker elk container
      docker_container:                                                                                                                                                                                                                                                                                                              name: elk                                                                                                                                                                                                                                                                                                                    image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Enable service docker on boot
      systemd:
        name: docker
        enabled: yes