---
- name: installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download metricbeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeat .deb
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Drop in metricbeat config
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker

  - name: setup metric beat
    command: metric beat setup

  - name: start metric beat
    command: service metric beat start

  - name: enable service metricbeat on boot
    systemd:
      name: metric beat
      enabled: yes